'use client';
import { useState } from 'react';
import { ArrowRight, Check, CheckCheck, Code2, Copy, KeyRound, Plus, ShieldCheck, Spade } from 'lucide-react';
import type { Filters, Project } from '@house-edge/shared';
import { mutate, type Action, type ViewProps } from './dashboard';
import { CodeBlock, Modal } from './ui';

export function ActionForm({ action, onClose, projects, project, view, filters, onSuccess, navigate }: {
  action: Exclude<Action, null>; onClose: () => void; projects: Project[]; project: string; view: string; filters: Filters;
  onSuccess: (message: string) => void; navigate: ViewProps['navigate'];
}) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [key, setKey] = useState(''); const [name, setName] = useState('');
  const [result, setResult] = useState<{ id: string; key: string; projectKey: string } | null>(null);
  const labels = { project: ['Connect a project', 'A small snippet. A whole new perspective.'], funnel: ['Create a funnel', 'Follow ordered events within the same session.'], feature: ['Track a feature', 'Give an important event a name and measure its adoption.'], alert: ['Create an alert', 'Get a signal when a measurable threshold is crossed.'], release: ['Record a release', 'Add a deployment marker and compare before and after.'], save: ['Save this view', 'Keep this date range, project, and filters for next time.'], dates: ['Choose a date range', 'All analytics use UTC. Select up to 366 days.'] };
  const origin = typeof window !== 'undefined' ? location.origin : 'http://localhost:3000';
  const projectSelect = (allowAll = false) => <label>Project<select name="projectId" defaultValue={project !== 'all' ? project : allowAll ? '' : projects[0]?.id} required={!allowAll}>{allowAll && <option value="">All projects</option>}{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>;
  async function submit(form: FormData) {
    setBusy(true); setError('');
    try {
      const values = Object.fromEntries(form.entries());
      if (action === 'project') {
        const domain = String(values.domain).replace(/^https?:\/\//, '').replace(/\/$/, '');
        const created = await mutate('projects', { name: values.name, projectKey: values.projectKey, domain, environment: values.environment, origins: String(values.origins || '').split(/[\n,]/).map(s => s.trim()).filter(Boolean).length ? String(values.origins).split(/[\n,]/).map(s => s.trim()).filter(Boolean) : [`${domain.startsWith('localhost') ? 'http' : 'https'}://${domain}`] });
        setResult(created); onSuccess('Project created. Copy your ingestion key before closing.');
      } else if (action === 'dates') {
        const from = new Date(`${values.from}T00:00:00.000Z`); const to = new Date(`${values.to}T23:59:59.999Z`);
        if (from > to || to.getTime() - from.getTime() > 366 * 86400000) throw new Error('Choose an end date after the start date, within 366 days.');
        navigate(view, { range: 'custom', from: from.toISOString(), to: new Date(Math.min(to.getTime(), Date.now())).toISOString() }); onClose();
      } else {
        const resource = { funnel: 'funnels', feature: 'features', alert: 'alerts', release: 'deployments', save: 'saved' }[action];
        const payload = action === 'funnel' ? { name: values.name, projectId: values.projectId || null, steps: String(values.steps).split(/\n|,/).map(s => s.trim()).filter(Boolean), windowHours: Number(values.windowHours) }
          : action === 'feature' ? { name: values.name, projectId: values.projectId, event: values.event }
          : action === 'alert' ? { name: values.name, projectId: values.projectId || null, metric: values.metric, operator: values.operator, threshold: Number(values.threshold), enabled: true }
          : action === 'release' ? { projectId: values.projectId, version: values.version, commitSha: values.commitSha, environment: values.environment }
          : { name: values.name, viewType: ['overview', 'events', 'sessions', 'users', 'errors', 'performance', 'features', 'retention', 'releases', 'projects', 'live', 'login-geography', 'geography'].includes(view) ? view : 'overview', filters: Object.fromEntries(Object.entries(filters).filter(([, v]) => v !== undefined)) };
        await mutate(resource, payload); onSuccess(`${action === 'save' ? 'View saved' : action === 'release' ? 'Release recorded' : action === 'feature' ? 'Feature tracked' : action === 'funnel' ? 'Funnel created' : 'Alert created'} successfully.`); onClose();
      }
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <Modal title={result ? 'You’re in the house.' : labels[action][0]} subtitle={result ? 'Your project is ready. Let’s give it a pulse.' : labels[action][1]} onClose={onClose} wide={!!result}>
    {result ? <><div className="success-callout"><ShieldCheck size={21} /><span><strong>Project connected</strong><small>This ingestion key is shown once. It can only send events from allowed origins.</small></span></div><CodeBlock code={`npm install @house-edge/analytics`} language="terminal" /><CodeBlock code={`import { houseEdge } from '@house-edge/analytics';\n\nhouseEdge.init({\n  projectKey: '${result.projectKey}',\n  key: '${result.key}',\n  endpoint: '${origin}/api/collect',\n  version: '1.0.0'\n});\n\n// Page views, sessions, errors, and Web Vitals are automatic.\nhouseEdge.track('feature_used', { feature: 'your-feature' });`} /><details className="embed-details"><summary>Prefer a script tag?</summary><CodeBlock code={`<script async\n  src="${origin}/house-edge.js"\n  data-project="${result.projectKey}"\n  data-key="${result.key}">\n</script>`} language="HTML" /></details><p className="fine-print">The SDK is built locally in this monorepo. Until published to your registry, install the package from packages/sdk-browser or use the script tag.</p><div className="modal-footer"><span className="fine-print">First events appear as soon as your app sends them.</span><button className="button primary" onClick={() => { navigate('projects', { project: result.id }); onClose(); }}>Open project <ArrowRight size={15} /></button></div></> : <form onSubmit={e => { e.preventDefault(); void submit(new FormData(e.currentTarget)); }}><fieldset disabled={busy} className="form-fields">
      {action === 'project' && <><label>Project name<input name="name" placeholder="e.g. Repo Reaper" value={name} onChange={e => { setName(e.target.value); setKey(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')); }} minLength={2} maxLength={120} required autoFocus /></label><label>Project key<input name="projectKey" value={key} onChange={e => setKey(e.target.value)} pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="repo-reaper" required /><small>A unique identifier used in your SDK configuration.</small></label><div className="form-row"><label>Application domain<input name="domain" placeholder="reporeaper.dev" required /></label><label>Environment<select name="environment"><option>production</option><option>staging</option><option>development</option></select></label></div><label>Allowed origins <span className="muted">(optional)</span><textarea name="origins" placeholder={'https://reporeaper.dev\nhttp://localhost:3000'} rows={2} /><small>One origin per line. Defaults to your application’s HTTPS origin.</small></label><div className="privacy-note"><ShieldCheck size={16} /><span>Private by default. No form contents, passwords, or sensitive query strings.</span></div></>}
      {action === 'funnel' && <><label>Funnel name<input name="name" placeholder="Repository activation" required maxLength={120} /></label>{projectSelect(true)}<label>Ordered events<textarea name="steps" defaultValue={'page_view\nlogin\nrepository_analyzed\nreadme_generated'} rows={5} required /><small>One exact event name per line. Between 2 and 8 steps.</small></label><label>Conversion window (hours)<input name="windowHours" type="number" min={1} max={168} defaultValue={24} required /></label></>}
      {action === 'feature' && <><label>Feature name<input name="name" placeholder="README Generator" required /></label>{projectSelect()}<label>Event name<input name="event" placeholder="readme_generated" required /><small>Usage, repeat usage, and growth are calculated from this event.</small></label></>}
      {action === 'alert' && <><label>Alert name<input name="name" placeholder="Elevated error rate" required /></label>{projectSelect(true)}<label>Metric<select name="metric"><option value="error_rate">Error rate (%) · last hour</option><option value="p95_latency">P95 latency (ms) · last hour</option><option value="silence_minutes">Minutes since the last event</option><option value="traffic_drop">Traffic drop (%) · previous hour</option><option value="conversion_drop">Conversion rate drop (%) · previous hour</option></select></label><div className="form-row"><label>Condition<select name="operator"><option value="gt">Greater than</option><option value="lt">Less than</option></select></label><label>Threshold<input name="threshold" type="number" step="any" min={0} max={100000} defaultValue={5} required /></label></div><p className="privacy-note">Alerts are evaluated by the maintenance job. Configure an HTTPS webhook on the server for notifications.</p></>}
      {action === 'release' && <>{projectSelect()}<div className="form-row"><label>Version<input name="version" placeholder="1.4.2" required maxLength={80} /></label><label>Commit SHA<input name="commitSha" placeholder="a1b2c3d" pattern="[a-fA-F0-9]*" maxLength={64} /></label></div><label>Environment<select name="environment"><option>production</option><option>staging</option><option>development</option></select></label><p className="fine-print">Records the current UTC timestamp. You can also create releases from CI using POST /api/deployments.</p></>}
      {action === 'save' && <><label>View name<input name="name" placeholder="Repo Reaper · Rust analysis" required maxLength={120} /></label><div className="saved-preview"><span>View<strong>{view}</strong></span><span>Project<strong>{projects.find(p => p.id === project)?.name || 'All projects'}</strong></span><span>Date range<strong>{filters.from.slice(0, 10)} → {filters.to.slice(0, 10)}</strong></span>{filters.search && <span>Search<strong>{filters.search}</strong></span>}</div></>}
      {action === 'dates' && <div className="form-row"><label>From<input name="from" type="date" defaultValue={filters.from.slice(0, 10)} required max={new Date().toISOString().slice(0, 10)} /></label><label>Through<input name="to" type="date" defaultValue={filters.to.slice(0, 10)} required max={new Date().toISOString().slice(0, 10)} /></label></div>}
      {error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="button" type="button" onClick={onClose}>Cancel</button><button className="button primary" type="submit" disabled={busy}>{busy ? 'Saving…' : action === 'dates' ? 'Apply date range' : labels[action][0]}{!busy && <ArrowRight size={15} />}</button></div>
    </fieldset></form>}
  </Modal>;
}
