'use client';
import { Activity, ArrowRight, Clock3, Globe, Monitor, MousePointer2, UserRound } from 'lucide-react';
import type { EventRow } from '@house-edge/shared';
import { useFetch, type ViewProps } from './dashboard';
import { CodeBlock, Loading, Modal, ProjectMark, date, duration, time } from './ui';

export function EventInspector({ event, onClose, navigate }: { event: EventRow; onClose: () => void; navigate: ViewProps['navigate'] }) {
  return <Modal wide title="Event details" subtitle="An individual event, exactly as it was collected." onClose={onClose}><div className="inspector-title"><ProjectMark name={event.project_name || event.project_id} color={event.color} /><div><h3>{event.event_name}</h3><p>{event.project_name} · {date(event.timestamp)}, {time(event.timestamp)} UTC</p></div><span className="badge neutral">{event.app_version ? `v${event.app_version}` : 'Unversioned'}</span></div><div className="detail-grid">{[['Route', event.path || '/'], ['Browser', event.browser], ['Device', `${event.device_type} / ${event.operating_system}`], ['Referrer', event.referrer || 'Direct'], ['Anonymous visitor', event.anonymous_id], ['Identified user', event.user_id || 'Not identified'], ['Duration', event.duration_ms == null ? '—' : duration(event.duration_ms)], ['Session', event.session_id]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><CodeBlock code={JSON.stringify(JSON.parse(event.properties_json), null, 2)} language="event properties · JSON" /><div className="modal-footer"><span className="fine-print">ID: {event.id}</span><button className="button primary" onClick={() => { navigate('sessions', { project: event.project_id, search: event.session_id }); onClose(); }}>Explore session <ArrowRight size={14} /></button></div></Modal>;
}
export function SessionInspector({ session, project, at, onClose }: { session: string; project: string; at: string; onClose: () => void }) {
  const { data, loading, error } = useFetch<EventRow[]>(`/api/session?project=${encodeURIComponent(project)}&session=${encodeURIComponent(session)}&to=${encodeURIComponent(at)}`);
  const first = data?.[0]; const last = data?.at(-1);
  return <Modal wide title="Session journey" subtitle="Reconstructed from events. No screen recording." onClose={onClose}>{loading ? <Loading /> : error ? <p className="form-error">{error}</p> : first && last ? <><div className="inspector-title"><ProjectMark name={first.project_name || ''} color={first.color} /><div><h3>{first.project_name}</h3><p>{date(first.timestamp)} · {time(first.timestamp)} UTC</p></div><span className="badge positive">{duration(Date.parse(last.timestamp) - Date.parse(first.timestamp))}</span></div><div className="session-stats"><span><Activity size={16} /><strong>{data?.length}</strong> events</span><span><Globe size={16} /><strong>{data?.filter(e => e.event_name === 'page_view').length}</strong> pages</span><span><Monitor size={16} />{first.browser} · {first.device_type}</span></div><div className="session-timeline">{data?.map(event => { const seconds = Math.floor((Date.parse(event.timestamp) - Date.parse(first.timestamp)) / 1000); return <div className={`timeline-item ${event.event_name === 'error' ? 'is-error' : ''}`} key={event.id}><time>{Math.floor(seconds / 60).toString().padStart(2, '0')}:{(seconds % 60).toString().padStart(2, '0')}</time><span className="timeline-dot" /><div><strong>{event.event_name === 'page_view' ? `Viewed ${event.path}` : event.event_name.replaceAll('_', ' ')}</strong><small>{event.path || '/'}{event.duration_ms != null && ` · ${duration(event.duration_ms)}`}</small><details><summary>Event properties</summary><pre>{JSON.stringify(JSON.parse(event.properties_json), null, 2)}</pre></details></div></div>; })}</div></> : <p>No events found for this session.</p>}</Modal>;
}
