'use client';
import { useCallback, useMemo, useState, type ReactNode } from 'react';
import { Activity, ArrowDown, ArrowDownRight, ArrowRight, ArrowUpRight, Bell, Bookmark, Box, Check, ChevronDown, ChevronRight, Clock3, Code2, Copy, Database, ExternalLink, Filter, Flame, GitBranch, Globe, KeyRound, Layers3, LoaderCircle, Monitor, MoreHorizontal, Network, Pause, Play, Plus, Radio, Search, Settings2, ShieldAlert, ShieldCheck, Skull, Sparkles, Star, Target, Trash2, TrendingUp, Users, Workflow, X, Zap } from 'lucide-react';
import { change, type EventRow, type Project } from '@house-edge/shared';
import type { Row } from '@house-edge/engine';
import { mutate, useFetch, type ViewProps } from './dashboard';
import { CodeBlock, DataTable, Delta, Empty, Loading, Modal, Panel, ProjectMark, date, duration, number, relativeTime, time, type Column } from './ui';
import { ProjectTable } from './overview';
import { EventInspector, SessionInspector } from './inspectors';
import { NetworkGraph } from './visualizations';
import { SettingsView, KeysView, Documentation } from './workspace-views';

const projectCell = (r: Row) => <span className="table-project"><span className="project-color-dot" style={{ background: String(r.color || '#6bcba3') }} />{r.project_name}</span>;
const numCell = (key: string) => (r: Row) => <span className="tabular">{number(Number(r[key]))}</span>;
const percentCell = (key: string) => (r: Row) => <span className="tabular">{Number(r[key]).toFixed(1)}%</span>;

export function AnalyticsView(props: ViewProps) {
  const { view, data, overview, projects, navigate, action, filters, search, setSearch, paused, setPaused } = props;
  if (view === 'docs') return <Documentation projects={projects} />;
  if (view === 'projects' && overview) return <><div className="project-card-grid">{overview.projects.map(p => <button className="project-card panel" key={p.id} onClick={() => navigate('projects', { project: p.id })}><div className="project-card-heading"><ProjectMark name={p.name} color={p.color} /><span className="badge neutral">{p.environment}</span><ChevronRight size={16} /></div><h3>{p.name}</h3><p>{p.domain}</p><div className="project-card-stats"><span><strong>{number(p.users)}</strong><small>visitors</small></span><span><strong>{number(p.events)}</strong><small>events</small></span><span><Delta value={p.change} /><small>traffic change</small></span></div><div className="project-card-footer"><span className={p.activeUsers ? 'live-dot' : 'status-dot inactive'} /><span>{p.activeUsers ? `${p.activeUsers} visitors active now` : 'Connected · waiting for activity'}</span><span>{p.errorRate.toFixed(2)}% errors</span></div></button>)}<button className="add-project-card" onClick={() => action('project')}><span><Plus size={23} /></span><h3>Your next project goes here.</h3><p>A tiny SDK. The whole story.</p><strong>Connect a project <ArrowRight size={14} /></strong></button></div><Panel title="Ecosystem breakdown" subtitle="Compare all projects in the selected period."><ProjectTable projects={overview.projects} navigate={navigate} /></Panel></>;
  if (view === 'pulse' && overview) return <div className="insight-grid">{overview.insights.map(insight => <button className={`insight-card panel ${insight.kind}`} key={insight.id} onClick={() => navigate(insight.metric === 'errors' ? 'errors' : 'projects', { project: insight.projectId })}><div><span className="insight-icon">{insight.kind === 'positive' ? <TrendingUp size={20} /> : <Activity size={20} />}</span><span className="badge neutral">{insight.metric === 'users' ? 'Traffic' : 'Observability'}</span></div><h3>{insight.title}</h3><p>{insight.detail}</p><span className="text-button">Explore the data <ArrowRight size={14} /></span></button>)}{!overview.insights.length && <Empty title="Your next insight starts with an event" />}</div>;
  if (view === 'compare') return <CompareView {...props} />;
  if (view === 'health' && overview) return <><div className="info-banner"><ShieldCheck size={18} /><span>Each indicator stands on its own. Traffic compares unique visitors with the previous period; error rate is errors divided by all events.</span></div><Panel><DataTable rows={overview.projects as unknown as Row[]} columns={[{ key: 'name', label: 'Project', render: r => <div className="project-name"><ProjectMark name={String(r.name)} color={String(r.color)} /><strong>{r.name}</strong></div> }, { key: 'change', label: 'Traffic change', render: r => <Delta value={Number(r.change)} /> }, { key: 'users', label: 'Visitors', render: numCell('users') }, { key: 'retentionRate', label: 'Retention', render: r => <span>{Number(r.retentionRate).toFixed(1)}%<small className="cell-sub"><Delta value={Number(r.retentionChange)} /></small></span> }, { key: 'avgDuration', label: 'Engagement', render: r => <span>{duration(Number(r.avgDuration))}<small className="cell-sub"><Delta value={Number(r.engagementChange)} /></small></span> }, { key: 'errorRate', label: 'Errors', render: r => <span>{Number(r.errorRate).toFixed(2)}% error rate<small className="cell-sub"><Delta value={Number(r.errorChange)} inverse /> occurrences</small></span> }, { key: 'p95Latency', label: 'P95 timing', render: r => <span>{duration(Number(r.p95Latency))}<small className="cell-sub"><Delta value={Number(r.performanceChange)} inverse /></small></span> }]} onRow={r => navigate('projects', { project: String(r.id) })} /></Panel></>;
  if (!data) return <Loading />;
  if (view === 'events' || view === 'live') return <EventsView {...props} />;
  if (view === 'sessions' || view === 'users') return <PeopleView {...props} />;
  if (['features', 'graveyard', 'rising'].includes(view)) return <FeatureView {...props} />;
  if (view === 'errors') return <ErrorsView {...props} />;
  if (view === 'performance') return <PerformanceView {...props} />;
  if (view === 'funnels') return <FunnelsView {...props} />;
  if (view === 'retention') return <RetentionView {...props} />;
  if (view === 'releases') return <ReleasesView {...props} />;
  if (view === 'ecosystem' || view === 'relationships' || view === 'journeys') return <PathsView {...props} />;
  if (view === 'heatmap') return <HeatmapView {...props} />;
  if (view === 'anomalies') return <><div className="info-banner"><Zap size={18} /><span>{(data.extra as { definition: string })?.definition}</span></div><div className="insight-grid">{data.rows.map(r => <div className="panel anomaly-card" key={String(r.id)}><div>{projectCell(r)}<span className={`badge ${r.severity === 'High' ? 'negative' : 'warning'}`}>{r.severity} deviation</span></div><h3>{r.metric} {Number(r.change) >= 0 ? 'increased' : 'decreased'} {Math.abs(Number(r.change)).toFixed(1)}%</h3><p>{number(Number(r.value))} observed vs. {number(Number(r.baseline))} daily baseline.</p><div className="anomaly-stats"><span><strong>{Number(r.z_score).toFixed(2)}σ</strong> from baseline</span><span>{r.samples} baseline days</span></div><button className="text-button" onClick={() => navigate(r.metric === 'errors' ? 'errors' : 'projects', { project: String(r.project_id) })}>Investigate project <ArrowRight size={14} /></button></div>)}</div>{!data.rows.length && <Panel><Empty title="Nothing out of the ordinary" description="No complete-day metrics crossed the statistical threshold. New projects need at least seven baseline days." /></Panel>}</>;
  if (view === 'saved') return <SavedViews {...props} />;
  if (view === 'alerts') return <AlertsView {...props} />;
  if (view === 'keys') return <KeysView {...props} />;
  if (view === 'settings') return <SettingsView {...props} />;
  return <Empty />;
}

function SummaryCards({ items }: { items: { label: string; value: ReactNode; detail?: string; icon?: ReactNode }[] }) { return <div className="summary-grid">{items.map(item => <div className="summary-card panel" key={item.label}><span>{item.label}{item.icon}</span><strong>{item.value}</strong>{item.detail && <small>{item.detail}</small>}</div>)}</div>; }
function SearchBox({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <div className="search-box"><Search size={15} /><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e => onChange(e.target.value)} />{value && <button className="icon-button" aria-label="Clear search" onClick={() => onChange('')}><X size={13} /></button>}</div>; }

function EventsView(props: ViewProps) {
  const { data, view, navigate, paused, setPaused, search, setSearch, filters } = props;
  const [selected, setSelected] = useState<EventRow | null>(null); const [advanced, setAdvanced] = useState(false);
  const [event, setEvent] = useState(filters.event || ''); const [property, setProperty] = useState(filters.property || ''); const [value, setValue] = useState(filters.value || ''); const [minimum, setMinimum] = useState(filters.minDuration?.toString() || '');
  if (!data) return null;
  const groups = data.extra as Row[] || [];
  const currentOffset = typeof window !== 'undefined' ? Number(new URLSearchParams(location.search).get('offset') || 0) : 0;
  const columns: Column[] = [
    { key: 'timestamp', label: 'Time (UTC)', render: r => <span className="event-time">{time(String(r.timestamp))}<small>{date(String(r.timestamp))}</small></span> },
    { key: 'project_name', label: 'Project', render: projectCell },
    { key: 'event_name', label: 'Event', render: r => <span className={`event-label ${r.event_name === 'error' ? 'error' : ''}`}><span />{r.event_name}</span> },
    { key: 'path', label: 'Route', render: r => <code className="route-code">{r.path || '/'}</code> },
    { key: 'session_id', label: 'Session', render: r => <code className="muted">{String(r.session_id).slice(0, 10)}…</code> },
    { key: 'device_type', label: 'Device', render: r => <span className="muted">{r.browser}<small className="cell-sub">{r.device_type}</small></span> },
    { key: 'id', label: '', render: () => <ChevronRight size={14} className="muted" /> },
  ];
  return <>{view === 'events' && <SummaryCards items={[{ label: 'Event occurrences', value: number(data.summary?.occurrences || 0), icon: <Activity size={16} /> }, { label: 'Unique visitors', value: number(data.summary?.users || 0), icon: <Users size={16} /> }, { label: 'Sessions', value: number(data.summary?.sessions || 0), icon: <Clock3 size={16} /> }, { label: 'Event types shown', value: groups.length, detail: 'Up to 30 most common event names', icon: <Layers3 size={16} /> }]} />}
    <Panel><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search events, routes, users, or versions…" /><div><button className={`button small ${advanced ? 'selected' : ''}`} onClick={() => setAdvanced(v => !v)}><Filter size={14} />Filters{(filters.event || filters.property || filters.minDuration) && <span className="filter-active-dot" />}</button>{view === 'live' && <button className={`button small ${paused ? '' : 'live-button'}`} onClick={() => setPaused(!paused)}>{paused ? <Play size={14} /> : <Pause size={14} />}{paused ? 'Resume feed' : 'Pause feed'}</button>}</div></div>
      {advanced && <form className="advanced-filters" onSubmit={e => { e.preventDefault(); navigate(view, { search, event, property, value, minDuration: minimum, offset: '0' }); }}><label>Event name<input value={event} onChange={e => setEvent(e.target.value)} placeholder="repository_analyzed" /></label><label>Property<input value={property} onChange={e => setProperty(e.target.value)} placeholder="language" pattern="[a-zA-Z0-9_]*" /></label><label>Equals<input value={value} onChange={e => setValue(e.target.value)} placeholder="Rust" /></label><label>Duration above (ms)<input type="number" min={0} value={minimum} onChange={e => setMinimum(e.target.value)} placeholder="1000" /></label><button className="button primary small" type="submit">Apply</button><button type="button" className="button small" onClick={() => { setEvent(''); setProperty(''); setValue(''); setMinimum(''); navigate(view, { event: '', property: '', value: '', minDuration: '', search, offset: '0' }); }}>Clear</button></form>}
      {view === 'live' && <div className="live-feed-status"><span className={paused ? 'status-dot inactive' : 'live-dot'} />{paused ? 'Feed paused. Your place is held.' : `Listening for events${props.overview?.demo ? ' · Demo activity is being generated' : ''}`}<span>Refreshes every 3 seconds</span></div>}
      <DataTable rows={data.rows} columns={columns} onRow={r => setSelected(r as unknown as EventRow)} foot={<><span>Showing {number(currentOffset + (data.rows.length ? 1 : 0))}–{number(currentOffset + data.rows.length)} of {number(data.total || 0)} events</span><div className="pagination"><button className="button small" disabled={currentOffset === 0} onClick={() => navigate(view, { search, offset: String(Math.max(0, currentOffset - 100)), event, property, value, minDuration: minimum })}>Previous</button><button className="button small" disabled={currentOffset + data.rows.length >= (data.total || 0)} onClick={() => navigate(view, { search, offset: String(currentOffset + 100), event, property, value, minDuration: minimum })}>Next <ChevronRight size={13} /></button></div></>} />
    </Panel>{view === 'events' && groups.length > 0 && <Panel title="Most frequent events" subtitle="The actions making up your selected activity." className="event-breakdown"><div className="event-bar-list">{groups.slice(0, 8).map(g => <button key={String(g.event_name)} onClick={() => navigate('events', { event: String(g.event_name) })}><code>{g.event_name}</code><div className="horizontal-bar"><span style={{ width: `${Number(g.count) / Number(groups[0].count) * 100}%` }} /></div><strong>{number(Number(g.count))}</strong><span>{number(Number(g.users))} visitors</span></button>)}</div></Panel>}{selected && <EventInspector event={selected} onClose={() => setSelected(null)} navigate={navigate} />}</>;
}

function PeopleView(props: ViewProps) {
  const [selected, setSelected] = useState<Row | null>(null); const { data, view, search, setSearch, navigate } = props;
  const columns: Column[] = view === 'sessions' ? [
    { key: 'session_id', label: 'Session', render: r => <span className="mono">{String(r.session_id).slice(0, 12)}…<small className="cell-sub">{date(String(r.first_seen))} · {time(String(r.first_seen))}</small></span> },
    { key: 'project_name', label: 'Project', render: projectCell },
    { key: 'duration_ms', label: 'Duration', render: r => duration(Number(r.duration_ms)) }, { key: 'page_views', label: 'Pages', render: numCell('page_views') }, { key: 'event_count', label: 'Events', render: numCell('event_count') },
    { key: 'landing_page', label: 'Entry → Exit', render: r => <span className="route-code">{r.landing_page || '/'}<small className="cell-sub">→ {r.exit_page || '/'}</small></span> },
    { key: 'browser', label: 'Device', render: r => <>{r.browser}<small className="cell-sub">{r.device_type}</small></> },
    { key: 'referrer', label: 'Referrer', render: r => <span className="truncate-cell">{r.referrer ? String(r.referrer).replace('https://', '') : 'Direct'}</span> },
  ] : [
    { key: 'anonymous_id', label: 'Anonymous visitor', render: r => <code>{String(r.anonymous_id).slice(0, 28)}</code> }, { key: 'project_name', label: 'Project', render: projectCell },
    { key: 'identified_user_id', label: 'Identified as' }, { key: 'sessions', label: 'Sessions', render: numCell('sessions') }, { key: 'events', label: 'Events', render: numCell('events') },
    { key: 'first_seen', label: 'First activity in range', render: r => date(String(r.first_seen)) }, { key: 'last_seen', label: 'Last activity', render: r => relativeTime(String(r.last_seen)) },
  ];
  return <Panel><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder={view === 'sessions' ? 'Search session ID, visitor, or referrer…' : 'Search visible visitors…'} /><span className="muted text-sm">{view === 'sessions' ? 'Click a session to follow its journey' : 'Click a visitor to explore their sessions'}</span></div><DataTable rows={view === 'users' && search ? data!.rows.filter(r => JSON.stringify(r).toLowerCase().includes(search.toLowerCase())) : data!.rows} columns={columns} onRow={r => view === 'sessions' ? setSelected(r) : navigate('sessions', { project: String(r.project_id), search: String(r.anonymous_id) })} foot={<span>Latest {data?.rows.length} {view} · maximum 200 per view</span>} />{selected && <SessionInspector session={String(selected.session_id)} project={String(selected.project_id)} at={props.filters.to} onClose={() => setSelected(null)} />}</Panel>;
}

function FeatureView(props: ViewProps) {
  const { data, view, navigate, action } = props; const [kind, setKind] = useState("all"); const rows = data!.rows.filter(r => kind === "all" || r.kind === kind);
  const open = (r: Row) => navigate("events", { project: String(r.project_id), event: String(r.event_name), search: r.kind === "Page" ? String(r.name) : "" });
  const tabs = <div className="view-toolbar"><div className="segmented">{["all", "Feature", "Page", "Event"].map(k => <button key={k} className={kind === k ? "selected" : ""} onClick={() => setKind(k)}>{k === "all" ? "All signals" : `${k}s`}</button>)}</div><span className="muted">{rows.length} measured signals</span></div>;
  if (view === 'graveyard') return <>{tabs}<div className="graveyard-banner"><Skull size={38} strokeWidth={1} /><div><h2>A little less code. A lot more clarity.</h2><p>Features, pages, and events with 3 or fewer users or a decline of at least 50%.</p></div><span>{rows.length}<small>features to reconsider</small></span></div><div className="feature-card-grid">{rows.map(r => <div className="panel graveyard-card" key={String(r.id)}><div>{projectCell(r)}<Skull size={17} /></div><h3>{r.name}</h3><span className="badge neutral">{r.kind}</span><p>{r.last_used ? `Last used ${r.days_inactive} days ago` : 'No recorded usage'}</p><div className="graveyard-card-stats"><span><strong>{r.users}</strong> visitors this period</span><Delta value={Number(r.change)} /></div><button className="text-button" onClick={() => open(r)}>Examine usage <ArrowRight size={14} /></button></div>)}</div>{!rows.length && <Panel><Empty title="Nothing gathering dust" description="Your tracked features are being used. No feature meets the low-usage threshold." /></Panel>}</>;
  if (view === 'rising') return <>{tabs}<div className="info-banner positive"><Flame size={18} /><span>A good run, backed by numbers. Features, pages, and events with more unique users than the previous period.</span></div><div className="feature-card-grid">{rows.map((r, i) => <button className="panel rising-card" key={String(r.id)} onClick={() => open(r)}><div><span className="rank">{String(i + 1).padStart(2, '0')}</span>{projectCell(r)}<TrendingUp size={18} /></div><h3>{r.name}</h3><strong className="rising-value">+{Number(r.change).toFixed(1)}<small>%</small></strong><p>{number(Number(r.users))} visitors · {number(Number(r.previous_users))} previously</p><span className="text-button">Explore this feature <ArrowRight size={14} /></span></button>)}</div>{!rows.length && <Panel><Empty title="Waiting for the next hot streak" description="No tracked features grew in this period. Try a wider date range." /></Panel>}</>;
  return <><SummaryCards items={[{ label: 'Tracked features', value: rows.length, icon: <Target size={16} /> }, { label: 'Growing features', value: rows.filter(r => Number(r.change) > 0).length, icon: <TrendingUp size={16} /> }, { label: 'Declining features', value: rows.filter(r => Number(r.change) < 0).length, icon: <ArrowDownRight size={16} /> }, { label: 'Feature events', value: number(rows.reduce((sum, r) => sum + Number(r.occurrences), 0)), icon: <Activity size={16} /> }]} /><Panel title="Features in focus" subtitle="Adoption is the percentage of a project’s visitors who used the feature."><DataTable rows={rows} columns={[{ key: 'name', label: 'Feature', render: r => <span><strong>{r.name}</strong><small className="cell-sub mono">{r.event_name}</small></span> }, { key: 'project_name', label: 'Project', render: projectCell }, { key: 'users', label: 'Visitors', render: numCell('users') }, { key: 'adoption', label: 'Adoption', render: r => <div className="adoption-cell"><span>{Number(r.adoption).toFixed(1)}%</span><div className="horizontal-bar"><span style={{ width: `${r.adoption}%` }} /></div></div> }, { key: 'change', label: 'Growth', render: r => <Delta value={Number(r.change)} /> }, { key: 'repeat_usage', label: 'Repeat usage', render: percentCell('repeat_usage') }, { key: 'retention', label: 'Retained visitors', render: percentCell('retention') }, { key: 'last_used', label: 'Last used', render: r => r.last_used ? date(String(r.last_used)) : 'Never' }]} onRow={r => navigate('events', { project: String(r.project_id), event: String(r.event_name) })} empty={<Empty title="Track what matters" description="Associate an event with a product feature to understand adoption, growth, and repeat usage." action={<button className="button primary" onClick={() => action('feature')}><Plus size={14} />Track a feature</button>} />} /></Panel></>;
}

function ErrorsView(props: ViewProps) {
  const { data } = props; const [selected, setSelected] = useState<Row | null>(null);
  return <><SummaryCards items={[{ label: 'Grouped issues', value: data!.summary?.issues || 0, icon: <ShieldAlert size={16} /> }, { label: 'Error occurrences', value: number(data!.summary?.occurrences || 0), icon: <Activity size={16} /> }, { label: 'Issue-session pairs', value: number(data!.summary?.affectedSessions || 0), detail: 'A session can encounter more than one issue', icon: <Users size={16} /> }]} /><Panel title="Issues" subtitle="Grouped by error name, message, and stack fingerprint."><DataTable rows={data!.rows} columns={[{ key: 'properties_json', label: 'Error', render: r => { const p = JSON.parse(String(r.properties_json)); return <span className="error-cell"><strong><span className="error-dot" />{p.name || 'Error'}</strong><small>{p.message || 'Unknown error'}</small></span>; } }, { key: 'project_name', label: 'Project', render: projectCell }, { key: 'occurrences', label: 'Occurrences', render: numCell('occurrences') }, { key: 'users_affected', label: 'Visitors affected', render: numCell('users_affected') }, { key: 'version', label: 'Version', render: r => <code className="version-badge">v{r.version}</code> }, { key: 'last_seen', label: 'Last seen', render: r => relativeTime(String(r.last_seen)) }]} onRow={setSelected} empty={<Empty title="A clean run" description="No errors were recorded in the selected period." />} /></Panel>{selected && <Modal wide title={String(JSON.parse(String(selected.properties_json)).name || 'Error')} subtitle={String(JSON.parse(String(selected.properties_json)).message)} onClose={() => setSelected(null)}><div className="detail-grid">{[['Project', selected.project_name], ['Occurrences', selected.occurrences], ['Visitors affected', selected.users_affected], ['Sessions affected', selected.sessions_affected], ['First seen', selected.first_seen], ['Last seen', selected.last_seen], ['Route', selected.path], ['Version', selected.version]].map(([label, value]) => <div key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div><CodeBlock language="stack trace" code={JSON.parse(String(selected.properties_json)).stack || 'No stack trace was supplied.'} /><button className="button" onClick={() => { props.navigate('events', { project: String(selected.project_id), event: 'error' }); setSelected(null); }}>Explore error events <ArrowRight size={14} /></button></Modal>}</>;
}

function PerformanceView(props: ViewProps) {
  const { data } = props; const [metric, setMetric] = useState('all'); const [version, setVersion] = useState('all');
  const [route, setRoute] = useState('all'); const [device, setDevice] = useState('all');
  const rows = data!.rows.filter(r => (metric === 'all' || r.metric === metric) && (version === 'all' || r.version === version) && (route === 'all' || r.path === route) && (device === 'all' || r.device === device));
  const fmt = (r: Row, key: string) => r.metric === 'CLS' ? Number(r[key]).toFixed(3) : duration(Number(r[key]));
  return <><SummaryCards items={['p50', 'p75', 'p95', 'p99'].map(m => ({ label: `${m.toUpperCase()} · all timing samples`, value: duration(data!.summary?.[m] || 0), detail: m === 'p50' ? 'Half of requests are faster than this' : `${m.slice(1)}% of requests are faster than this`, icon: <Clock3 size={16} /> }))} /><div className="vitals-guide"><span><span className="status-dot" />Good Web Vitals at P75</span><code>LCP ≤ 2.5s</code><code>INP ≤ 200ms</code><code>CLS ≤ 0.1</code><span className="muted">CLS is unitless and excluded from timing totals.</span></div><Panel><div className="table-toolbar performance-filters">{([{ key: 'metric', label: 'All metrics', value: metric, setter: setMetric }, { key: 'version', label: 'All versions', value: version, setter: setVersion }, { key: 'path', label: 'All routes', value: route, setter: setRoute }, { key: 'device', label: 'All devices', value: device, setter: setDevice }] as const).map(item => <label className="select-button" key={item.key}><select aria-label={item.label} value={item.value} onChange={e => item.setter(e.target.value)}><option value="all">{item.label}</option>{[...new Set(data!.rows.map(r => String(r[item.key])))].map(v => <option key={v}>{v}</option>)}</select><ChevronDown size={13} /></label>)}</div><DataTable rows={rows} columns={[{ key: 'metric', label: 'Metric', render: r => <code className="text-bright">{r.metric}</code> }, { key: 'project_name', label: 'Project', render: projectCell }, { key: 'path', label: 'Route / version', render: r => <span className="mono">{r.path}<small className="cell-sub">v{r.version}</small></span> }, { key: 'browser', label: 'Client', render: r => <span>{r.browser}<small className="cell-sub">{r.device}</small></span> }, { key: 'samples', label: 'Samples', render: numCell('samples') }, ...['p50', 'p75', 'p95', 'p99'].map(key => ({ key, label: key.toUpperCase(), render: (r: Row) => <span className={key === 'p95' && Number(r[key]) > 2000 ? 'text-amber tabular' : 'tabular'}>{fmt(r, key)}</span> }))]} foot={<span>{number(data!.summary?.samples || 0)} samples · exact percentiles over up to 100,000 most recent timing events</span>} /></Panel></>;
}

interface Funnel { id: string; name: string; project_name: string; steps: string[]; counts: number[]; previous: number[]; timeToConvert: number; window_hours: number; }
function FunnelsView(props: ViewProps) {
  const funnels = props.data!.extra as Funnel[]; const [selected, setSelected] = useState('');
  const funnel = funnels.find(f => f.id === selected) || funnels[0];
  if (!funnel) return <Panel><Empty title="Every conversion has a story" description="Create a funnel from ordered events to see where users make progress and where they leave." action={<button className="button primary" onClick={() => props.action('funnel')}><Plus size={14} />Create a funnel</button>} /></Panel>;
  const conversion = funnel.counts[0] ? funnel.counts.at(-1)! / funnel.counts[0] * 100 : 0;
  const previous = funnel.previous[0] ? funnel.previous.at(-1)! / funnel.previous[0] * 100 : 0;
  return <><div className="view-toolbar"><label className="select-button"><Target size={16} /><select aria-label="Choose funnel" value={funnel.id} onChange={e => setSelected(e.target.value)}>{funnels.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select><ChevronDown size={14} /></label><span className="muted">{funnel.project_name || 'All projects'} · {funnel.window_hours}-hour window · same session</span></div><SummaryCards items={[{ label: 'Overall conversion', value: `${conversion.toFixed(1)}%`, detail: `${previous.toFixed(1)}% in the previous period` }, { label: 'Sessions entered', value: number(funnel.counts[0] || 0) }, { label: 'Sessions converted', value: number(funnel.counts.at(-1) || 0) }, { label: 'Average time to convert', value: duration(funnel.timeToConvert) }]} /><Panel title={funnel.name} subtitle="A session must complete each step in order to progress."><div className="funnel-chart">{funnel.steps.map((step, i) => { const percent = funnel.counts[0] ? funnel.counts[i] / funnel.counts[0] * 100 : 0; const retained = i && funnel.counts[i - 1] ? funnel.counts[i] / funnel.counts[i - 1] * 100 : 100; return <div className="funnel-step" key={i}><div className="funnel-step-title"><span>{String(i + 1).padStart(2, '0')}</span><code>{step}</code></div><strong>{number(funnel.counts[i])}<small>{percent.toFixed(1)}%</small></strong><div className="funnel-bar-container"><div className="funnel-bar" style={{ height: `${Math.max(percent, 2)}%`, opacity: 1 - i * .1 }}><span>{number(funnel.counts[i])}</span></div></div><div className="funnel-step-footer">{i ? <><ArrowDown size={13} />{(100 - retained).toFixed(1)}% drop-off</> : 'Starting point'}</div></div>; })}</div></Panel><div className="info-banner"><Clock3 size={16} /><span>Previous period conversion: {previous.toFixed(1)}% → current period: {conversion.toFixed(1)}%. Median and cross-session attribution are not used in this funnel.</span></div></>;
}

function RetentionView(props: ViewProps) {
  const featureData = useFetch<{ rows: Row[] }>(`/api/data?view=features&${props.query}`);
  const data = props.data!; const interval = (data.extra as { interval: string })?.interval || 'weekly';
  const unit = interval === 'daily' ? 'Day' : interval === 'monthly' ? 'Month' : 'Week';
  return <><div className="view-toolbar"><div className="segmented">{['daily', 'weekly', 'monthly'].map(i => <button key={i} className={interval === i ? 'selected' : ''} onClick={() => props.navigate('retention', { interval: i, event: props.filters.event || '' })}>{i[0].toUpperCase() + i.slice(1)}</button>)}</div><label className="select-button"><select aria-label="Retention event" value={props.filters.event || ""} onChange={e => props.navigate("retention", { event: e.target.value, interval })}><option value="">All activity · first-ever visitors</option>{[...new Set(featureData.data?.rows.map(r => String(r.event_name)) || [])].map(event => <option key={event} value={event}>{event}</option>)}</select><ChevronDown size={13} /></label></div><Panel title="Do they come back?" subtitle="Each row groups visitors by when they first appeared. Cells show the percentage who returned."><div className="table-scroll"><table className="retention-table"><thead><tr><th>Cohort</th><th>Visitors</th>{Array.from({ length: 8 }, (_, i) => <th key={i}>{unit} {i}</th>)}</tr></thead><tbody>{data.rows.map(r => <tr key={String(r.cohort)}><td>{date(String(r.cohort))}</td><td>{number(Number(r.users))}</td>{Array.from({ length: 8 }, (_, i) => <td key={i}>{r[`period_${i}`] === null ? <span className="cohort-cell unavailable">—</span> : <span className="cohort-cell" style={{ backgroundColor: `rgba(77, 188, 143, ${.08 + Number(r[`period_${i}`]) / 100 * .68})`, color: Number(r[`period_${i}`]) > 60 ? '#e7fff3' : '#99c9b1' }}>{r[`period_${i}`]}%</span>}</td>)}</tr>)}</tbody></table></div>{!data.rows.length && <Empty title="No new cohorts in this period" description="Try the last 90 days to include your visitors’ first activity. Returning visitors only appear in their original cohort." />}<div className="table-footer"><span>Incomplete future periods are shown as — · monthly periods are 30 days</span><div className="heatmap-legend">Less<span style={{ background: '#17271f' }} /><span style={{ background: '#24523c' }} /><span style={{ background: '#327650' }} /><span style={{ background: '#409c6d' }} />More</div></div></Panel></>;
}

function ReleasesView(props: ViewProps) {
  const [selected, setSelected] = useState<Row | null>(null);
  return <><div className="info-banner"><GitBranch size={17} /><span>Compare equal windows up to 24 hours before and after a deployment. Recent releases use the time elapsed since deployment.</span></div><div className="release-list">{props.data!.rows.map(r => <button className="panel release-card" key={String(r.id)} onClick={() => setSelected(r)}><div className="release-leading"><span className="release-node"><GitBranch size={19} /></span><div><h3>{r.project_name}<code>v{r.version}</code><span className="badge neutral">{r.environment}</span></h3><p><code>{r.commit_sha}</code><span>·</span>{date(String(r.deployed_at))} at {time(String(r.deployed_at))} UTC</p></div></div><div className="release-metrics"><span><small>Traffic change</small><Delta value={Number(r.traffic_change)} /></span><span><small>Error rate</small><strong>{Number(r.error_rate_before).toFixed(2)}% <ArrowRight size={12} /> {Number(r.error_rate_after).toFixed(2)}%</strong></span><span><small>Avg. latency</small><strong>{r.latency_after == null ? 'No samples' : duration(Number(r.latency_after))}</strong></span><ChevronRight size={17} /></div></button>)}</div>{!props.data!.rows.length && <Panel><Empty title="Your next release starts a new chapter" description="Record a deployment to compare traffic, errors, performance, and conversions before and after." action={<button className="button primary" onClick={() => props.action('release')}>Add a release</button>} /></Panel>}{selected && <Modal wide title={`${selected.project_name} · v${selected.version}`} subtitle={`${Number(selected.window_hours).toFixed(1)}-hour comparison windows around this deployment.`} onClose={() => setSelected(null)}><table className="data-table comparison-table"><thead><tr><th>Indicator</th><th>Before release</th><th>After release</th></tr></thead><tbody>{[['Unique visitors', 'users_before', 'users_after', 'number'], ['Errors', 'errors_before', 'errors_after', 'number'], ['Error rate', 'error_rate_before', 'error_rate_after', 'percent'], ['Conversion events / session', 'conversion_before', 'conversion_after', 'percent'], ['Average session', 'engagement_before', 'engagement_after', 'duration'], ['Average timing sample', 'latency_before', 'latency_after', 'duration']].map(([label, a, b, format]) => <tr key={label}><td>{label}</td>{[a, b].map(k => <td key={k}>{selected[k] == null ? 'No samples' : format === 'duration' ? duration(Number(selected[k])) : format === 'percent' ? `${Number(selected[k]).toFixed(2)}%` : number(Number(selected[k]))}</td>)}</tr>)}</tbody></table><p className="fine-print">This is an observational comparison around the deployment timestamp, not proof that the release caused the changes.</p></Modal>}</>;
}

function PathsView(props: ViewProps) {
  const { data, view, navigate } = props;
  const extra = data!.extra as { links: { source: string; target: string; count: number }[]; sampled: boolean; definition?: string };
  if (view === 'journeys') {
    const totals = new Map<string, number>(); extra.links.forEach(l => totals.set(l.source, (totals.get(l.source) || 0) + l.count));
    return <><SummaryCards items={[{ label: 'Distinct actions', value: data!.rows.length, icon: <Activity size={16} /> }, { label: 'Observed transitions', value: number(extra.links.reduce((n, l) => n + l.count, 0)), icon: <Workflow size={16} /> }, { label: 'Common paths', value: extra.links.length, icon: <Network size={16} /> }]} /><Panel title="The paths most traveled" subtitle="Consecutive actions within the same project and session."><div className="journey-list">{extra.links.slice(0, 20).map((link, i) => <div className="journey-row" key={i}><span className="rank">{String(i + 1).padStart(2, '0')}</span><code>{link.source}</code><div className="journey-connection"><span style={{ height: `${Math.max(2, link.count / (extra.links[0]?.count || 1) * 8)}px` }} /><ArrowRight size={14} /></div><code>{link.target}</code><strong>{number(link.count)}<small>transitions</small></strong><span className="badge neutral">{(link.count / (totals.get(link.source) || 1) * 100).toFixed(1)}% of next actions</span></div>)}</div>{!extra.links.length && <Empty />}<div className="table-footer"><span>Calculated from the latest 50,000 matching events. Percentages measure observed next actions; session exits are excluded.</span></div></Panel></>;
  }
  return <><Panel title={view === 'ecosystem' ? 'Your software universe' : 'Patterns in the constellation'} subtitle={view === 'ecosystem' ? 'Node size reflects observed event volume. Connections represent cross-project referrals.' : 'Event frequency determines node size. Connections show consecutive events within a session.'} action={<span className="badge neutral">{data!.rows.length} nodes</span>}><NetworkGraph nodes={data!.rows} links={extra.links} onNode={id => navigate(view === 'ecosystem' ? 'projects' : 'events', view === 'ecosystem' ? { project: id } : { event: id })} /><div className="table-footer"><span><span className="legend-dot green" />{view === 'ecosystem' ? 'Click a project to explore its analytics' : 'Click an event to open Event Explorer'}</span><span>Up to 50,000 recent matching events{extra.sampled ? ' · sample limit reached' : ''}</span></div></Panel><Panel title="Strongest connections" className="connections-panel"><DataTable rows={extra.links.slice(0, 12).map(l => ({ source: data!.rows.find(n => n.id === l.source)?.name || l.source, target: data!.rows.find(n => n.id === l.target)?.name || l.target, count: l.count }))} columns={[{ key: 'source', label: 'From' }, { key: 'target', label: 'To' }, { key: 'count', label: 'Transitions', render: numCell('count') }]} /></Panel></>;
}

function HeatmapView(props: ViewProps) {
  const [metric, setMetric] = useState('events');
  const rows = props.data!.rows; const map = new Map(rows.map(r => [String(r.date).slice(0, 10), Number(r[metric]) || 0]));
  const start = new Date(props.filters.from.slice(0, 10) + 'T00:00:00Z').getTime(); const end = Date.parse(props.filters.to);
  const days = Array.from({ length: Math.min(366, Math.floor((end - start) / 86400000) + 1) }, (_, i) => new Date(start + i * 86400000).toISOString().slice(0, 10));
  const max = Math.max(1, ...map.values());
  return <Panel title="Every day adds up" subtitle={`${number([...map.values()].reduce((a, b) => a + b, 0))} ${metric} in the selected period`} action={<label className="select-button"><select aria-label="Heatmap metric" value={metric} onChange={e => setMetric(e.target.value)}><option value="events">Events</option><option value="users">Visitors</option><option value="sessions">Sessions</option><option value="pageViews">Page views</option><option value="errors">Errors</option><option value="conversions">Conversions</option></select><ChevronDown size={13} /></label>}><div className="heatmap-container"><div className="heatmap-days"><span>Mon</span><span>Wed</span><span>Fri</span></div><div className="activity-heatmap">{Array.from({ length: new Date(start).getUTCDay() }, (_, i) => <span className="heatmap-spacer" key={`empty${i}`} />)}{days.map(day => <button className="heatmap-cell" key={day} title={`${day}: ${number(map.get(day) || 0)} ${metric}`} aria-label={`${day}: ${map.get(day) || 0} ${metric}`} style={{ background: `rgba(81, 193, 145, ${.06 + (map.get(day) || 0) / max * .84})` }} onClick={() => props.navigate('snapshot', { range: 'custom', from: `${day}T00:00:00.000Z`, to: `${day}T23:59:59.999Z` })} />)}</div></div><div className="table-footer"><span>Click a day to open its historical snapshot.</span><div className="heatmap-legend">Less{[.1, .3, .5, .7, .9].map(o => <span key={o} style={{ background: `rgba(81,193,145,${o})` }} />)}More</div></div></Panel>;
}

function CompareView(props: ViewProps) {
  const [a, setA] = useState(''); const [b, setB] = useState('');
  const items = props.overview?.projects || []; const left = items.find(p => p.id === a) || items[0]; const right = items.find(p => p.id === b) || items.find(p => p.id !== left?.id);
  if (items.length < 2 || !left || !right) return <Panel><Empty title="It takes two to compare" description="Choose All projects in the project filter, or connect another application." action={<button className="button" onClick={() => props.navigate('compare', { project: 'all' })}>Show all projects</button>} /></Panel>;
  return <Panel className="compare-panel"><div className="compare-heading"><span className="eyebrow">HEAD TO HEAD</span><h2>A little healthy competition.</h2><p>Independent projects. The same measuring stick.</p></div><div className="versus-header">{[left, right].map((p, i) => <div key={i}><ProjectMark name={p.name} color={p.color} /><select aria-label={i === 0 ? 'First project' : 'Second project'} value={p.id} onChange={e => i === 0 ? setA(e.target.value) : setB(e.target.value)}>{items.filter(x => x.id !== (i === 0 ? right.id : left.id)).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><small>{p.domain}</small></div>)}<span className="versus-badge">VS</span></div><div className="comparison-rows">{[['Visitors', 'users', 'number'], ['Sessions', 'sessions', 'number'], ['Retention', 'retentionRate', 'percent'], ['P95 latency', 'p95Latency', 'duration'], ['Events', 'events', 'number'], ['Page views', 'pageViews', 'number'], ['Average session', 'avgDuration', 'duration'], ['Conversions', 'conversions', 'number'], ['Error rate', 'errorRate', 'percent'], ['Traffic growth', 'change', 'percent']].map(([label, key, type]) => { const va = Number(left[key as keyof typeof left]); const vb = Number(right[key as keyof typeof right]); const max = Math.max(va, vb, 1); const format = (n: number) => type === 'duration' ? duration(n) : type === 'percent' ? `${n.toFixed(1)}%` : number(n); return <div key={key}><strong style={{ color: left.color }}>{format(va)}</strong><span>{label}<div className="comparison-bars"><i style={{ width: `${Math.max(2, va / max * 50)}%`, background: left.color }} /><i style={{ width: `${Math.max(2, vb / max * 50)}%`, background: right.color }} /></div></span><strong style={{ color: right.color }}>{format(vb)}</strong></div>; })}</div></Panel>;
}

function SavedViews(props: ViewProps) {
  const [deleting, setDeleting] = useState<string | null>(null);
  return <><div className="saved-grid">{props.data!.rows.map(r => <div className="panel saved-card" key={String(r.id)}><div><span className="saved-icon"><Star size={18} /></span><button className="icon-button" aria-label={`Delete ${r.name}`} onClick={() => setDeleting(String(r.id))}><Trash2 size={15} /></button></div><h3>{r.name}</h3><span className="badge neutral">{String(r.view_type).replaceAll('_', ' ')}</span><p>{Object.entries(JSON.parse(String(r.filters_json))).filter(([k]) => !['from', 'to'].includes(k)).map(([k, v]) => `${k}: ${k === 'project' ? props.projects.find(p => p.id === v)?.name || v : v}`).join(' · ') || 'All projects'}</p><button className="text-button" onClick={() => props.navigate(String(r.view_type), { ...JSON.parse(String(r.filters_json)), range: 'custom' })}>Open saved view <ArrowRight size={14} /></button></div>)}</div>{!props.data!.rows.length && <Panel><Empty title="Keep a good perspective" description="Use the star in the filter bar to save any analytics view, including its project, dates, and filters." action={<button className="button primary" onClick={() => props.navigate('events')}>Explore events <ArrowRight size={14} /></button>} /></Panel>}{deleting && <Modal title="Delete this saved view?" subtitle="Your collected analytics data will be kept." onClose={() => setDeleting(null)}><div className="modal-footer"><button className="button" onClick={() => setDeleting(null)}>Cancel</button><button className="button danger" onClick={async () => { try { await mutate('delete', { id: deleting, type: 'saved_views' }); props.refresh(); props.toast('Saved view deleted.'); setDeleting(null); } catch (e) { props.toast((e as Error).message); } }}>Delete view</button></div></Modal>}</>;
}

function AlertsView(props: ViewProps) {
  const [busy, setBusy] = useState(false); const [deleting, setDeleting] = useState<Row | null>(null); const incidents = props.data!.extra as Row[];
  const evaluate = async () => { setBusy(true); try { const res = await mutate('maintenance', {}); props.toast(`Evaluated ${res.evaluated} rules; ${res.triggered} new incidents. Retention cleanup completed.`); props.refresh(); } catch (e) { props.toast((e as Error).message); } finally { setBusy(false); } };
  return <><div className="info-banner"><Bell size={18} /><span>Rules are evaluated by your scheduled maintenance job. Notifications use the server’s configured webhook, with one incident per rule per hour.</span><button className="button small" disabled={busy} onClick={evaluate}>{busy ? <LoaderCircle size={14} className="spin" /> : <Play size={14} />}Run maintenance</button></div><Panel title="Alert rules" subtitle="Each rule watches an independent, measurable signal."><DataTable rows={props.data!.rows} columns={[{ key: 'name', label: 'Alert', render: r => <strong>{r.name}</strong> }, { key: 'project_name', label: 'Project', render: r => r.project_name || 'All projects' }, { key: 'metric', label: 'Condition', render: r => <code>{String(r.metric).replaceAll('_', ' ')} {r.operator === 'gt' ? '>' : '<'} {r.threshold}</code> }, { key: 'enabled', label: 'Status', render: r => <button role="switch" aria-checked={!!r.enabled} className={`toggle ${r.enabled ? 'on' : ''}`} aria-label={`Toggle ${r.name}`} onClick={async () => { try { await mutate('alert-toggle', { id: r.id, enabled: !r.enabled }); props.refresh(); } catch (e) { props.toast((e as Error).message); } }}><span /></button> }, { key: 'id', label: '', render: r => <button className="icon-button" aria-label={`Delete ${r.name}`} onClick={() => setDeleting(r)}><Trash2 size={14} /></button> }]} empty={<Empty title="A quiet room, with a watchful eye" description="Create your first alert to know when errors, latency, or traffic cross a threshold." />} /></Panel><Panel title="Recent incidents" className="connections-panel"><DataTable rows={incidents || []} columns={[{ key: 'message', label: 'What happened' }, { key: 'created_at', label: 'Detected', render: r => `${date(String(r.created_at))} · ${time(String(r.created_at))}` }, { key: 'notified_at', label: 'Notification', render: r => <span className={`badge ${r.notified_at ? 'positive' : 'neutral'}`}>{r.notified_at ? 'Delivered' : 'Pending provider'}</span> }]} empty={<Empty title="No alert incidents" description="Incidents appear here when an enabled rule crosses its threshold." />} /></Panel>{deleting && <Modal title={`Delete “${deleting.name}”?`} subtitle="This removes the rule and its incident history." onClose={() => setDeleting(null)}><div className="modal-footer"><button className="button" onClick={() => setDeleting(null)}>Cancel</button><button className="button danger" onClick={async () => { try { await mutate('delete', { id: deleting.id, type: 'alerts' }); props.refresh(); setDeleting(null); } catch (e) { props.toast((e as Error).message); } }}>Delete alert</button></div></Modal>}</>;
}
